name: Hello World on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
